version: '3.8'

services:
  simprint-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BINARY_NAME: simprint-server
    container_name: simprint-client-gateway
    command: ["-f=/app/configs/config.prod.toml"]
    ports:
      - "40041:40041"
    volumes:
      - ./configs:/app/configs:ro
      - ./assets:/app/assets:ro
    environment:
      - RUST_LOG=info
    restart: unless-stopped
    networks:
      - simprint-network

networks:
  simprint-network:
    external: true
