[app]
name = "update-gateway"
port = 40042
secret = "p4y8uX1Jc22K7bAN52arpvJpVbduUvGNNNfo"
prefix = "/api/v1"
encrypt_secret_location = "./assets/secret"
route_whitelists = [
    "POST+/api/v1/versions/check",
    "POST+/api/v1/maintenances/active",
    "GET+/api/v1/health"
]

[database]
url = "postgres://lius:0gMAZGgriRK395Apzcb8@111.230.19.75:5433/simprintdb"
max_connections = 25
min_connections = 5
max_lifetime = 3000
acquire_timeout = 30
idle_timeout = 600

[redis]
url = "redis://111.230.19.75:6380?protocol=resp3"

