[app]
name = "simprint-server"
port = 40041
secret = "p4y8uX1Jc22K7bAN52arpvJpVbduUvGNNNfo"
prefix = "/api/v1"
encrypt_secret_location = "./assets/secret"
route_whitelists = [
    "POST+/api/v1/users/login",
    "POST+/api/v1/users/register",
    "POST+/api/v1/users/register-send-code",
    "POST+/api/v1/users/reset-password",
    "POST+/api/v1/users/reset-password-send-code",
    "POST+/api/v1/users/refresh-credentials",
    "GET+/api/v1/secret/public/key",
    "GET+/api/v1/time/now",
    "POST+/api/v1/versions/check"
]
referral_link_prefix = "https://www.simprint.app/download"


[database]
url = "postgres://lius:0gMAZGgriRK395Apzcb8@postgresql-pro:5432/simprintdb"
max_connections = 25
min_connections = 5
max_lifetime = 3000
acquire_timeout = 30
idle_timeout = 600

[redis]
url = "redis://redis-server-pro:6379?protocol=resp3"

[storage]
endpoint = "https://503bc762ec98603e9ff53f374d78df22.r2.cloudflarestorage.com"
public_base_url = "https://pub-39307a5e69c74324855a762027cbf9bf.r2.dev"
access_key = "9295bc8f31a4bc6ce80d0014e29e6896"
secret_access_key = "60a9cd6d3dd6b10ea0f0aaf2411c127bfb01ef8700a62bf8cb3a8bf6c3bb6d73"
bucket = "simprint-client"
avatar_root = "avatars"
extension_root = "extensions"
version_root = "versions"

[smtp]
smtp_server = "smtp.163.com"
smtp_username = "liushuinew@163.com"
smtp_password = "NSgjTyY6uSQwPGwV"

[workspace_quota]
# 默认配额（新用户注册和手动创建工作空间都使用此配置）
[workspace_quota.default]
max_environments = 8
max_team_members = 1
max_proxies = 99999
max_rpa_tasks = 99999
